/**
 * Compiles contracts/ArcPayDemoNFT.sol via solc and writes the ABI +
 * bytecode to src/chain/nftArtifact.ts as a plain TS module (no JSON
 * import machinery needed, and it's typed for free).
 *
 *   npx tsx scripts/compile-nft.ts
 */
import { readFileSync, writeFileSync } from "node:fs";
import solc from "solc";

const source = readFileSync("contracts/ArcPayDemoNFT.sol", "utf8");

const input = {
  language: "Solidity",
  sources: { "ArcPayDemoNFT.sol": { content: source } },
  settings: {
    optimizer: { enabled: true, runs: 200 },
    outputSelection: { "*": { "*": ["abi", "evm.bytecode.object"] } },
  },
};

const output = JSON.parse(solc.compile(JSON.stringify(input)));

const errors = (output.errors ?? []).filter((e: { severity: string }) => e.severity === "error");
if (errors.length) {
  for (const e of output.errors) console.error(e.formattedMessage);
  throw new Error(`Compilation failed with ${errors.length} error(s).`);
}
for (const w of output.errors ?? []) console.warn(w.formattedMessage);

const contract = output.contracts["ArcPayDemoNFT.sol"]["ArcPayDemoNFT"];
const abi = contract.abi;
const bytecode = "0x" + contract.evm.bytecode.object;

writeFileSync(
  "src/chain/nftArtifact.ts",
  `/** Auto-generated by scripts/compile-nft.ts — do not hand-edit. Re-run the script after changing contracts/ArcPayDemoNFT.sol. */
export const NFT_ABI = ${JSON.stringify(abi, null, 2)} as const;
export const NFT_BYTECODE = "${bytecode}" as const;
`,
);

console.log(`Compiled OK. Bytecode length: ${bytecode.length} chars. ABI entries: ${abi.length}.`);
